name: eeg

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.10
  - numpy
  - matplotlib
  - pandas
  - jupyterlab
  - partd
  - bokeh
  - nbdev
  - pip
  - pip:
    - scipy
    - scikit-learn
    - seaborn
#    - h5py
#    - Oct2py
    
