# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EEG-Familiarity',
                'doc_host': 'https://FleischerResearchLab.github.io',
                'git_url': 'https://github.com/FleischerResearchLab/EEG-Familiarity',
                'lib_path': 'EEG_Familiarity'},
  'syms': {'EEG_Familiarity.core': {'EEG_Familiarity.core.foo': ('core.html#foo', 'EEG_Familiarity/core.py')}}}
